% -------------------------------------------------------------------
%  Generated by MATLAB on 7-Feb-2017 19:39:57
%  MATLAB version: 9.0.0.341360 (R2016a)
% -------------------------------------------------------------------
saveVarsMat = load('bbc.mat');

MAT = saveVarsMat.MAT; % <9635x2225 double> too many elements

clear saveVarsMat;
